### ISSUE TITLE
What is the reason for the 0.04 margin?

### ISSUE THREAD

**Issue by MovingtoMars** [sebcrozet/nphysics#51]
It just ends up with code like in [examples2/pyramid.rs](https://github.com/sebcrozet/nphysics/blob/master/examples2/pyramid.rs#L41). I'm working on a project with nphysics and have to subtract 0.04 from all widths etc for the objects to be the right size.

**Comment by sebcrozet** [comment]
Collision margins improve dramatically collision detection times and accuracy by allowing the use of distance computation algorithms to compute penetration depths. Also, by smoothing rough edges, it helps reduce simulation artifacts due to the discrete nature of the geometric models.

The use of margins (and thus a pre-erosion of geometric models) is  common on most physics engines I know (Box2D, Bullet) and even proprietary engines that attempt to be more realistic for engineering purposes.

The exact value 0.04 is kind of arbitrary though. It cannot be changed by the user yet but will in the future.

**Comment by MovingtoMars** [comment]
Couldn't the margin be automatically deducted off of the shape dimensions, so the output is what's expected?

**Comment by sebcrozet** [comment]
Not really. This could be done for some specific shapes like boxes and balls (which is what Bullet does), but for other shapes it might lead to unwanted results. For example auto-eroding a triangle meshes might cause self-intersections on thin parts.
